### PR TITLE
Fix typos and markdownlint

### PR DESCRIPTION
**Pull request by friederbluemle**
This fixes several minor typos, e.g.:

- `Github` -> `GitHub`
- `Cocoapods` -> `CocoaPods`
- `Fastlane` -> `fastlane`

In a separate commit, it fixes all whitespace errors and [markdownlint](https://github.com/markdownlint/markdownlint) (except MD013) in the docs and markdown files.

Also contains a small update to `.gitignore`

### CODE REVIEW

**Comment by ruddell** [comment]
Thanks for this! 👍 

It might be handy for future updates to know how this was done.  Did you make these changes manually, or use a tool to automate it?

**Comment by friederbluemle** [comment]
@ruddell - Most of the Markdown fixes were done manually, checking output of `markdownlint` on command line.
https://github.com/markdownlint/markdownlint

An easy way to check any Git repository for whitespace errors is comparing the working directory content against the empty tree object:

    git diff --check 4b825dc642cb6eb9a060e54bf8d69288fbee4904

(it's not easy to remember, so I have an alias for it ;))

This can also be seen in `.git/hooks/pre-commit.sample` of a Git repository.

There are tools (e.g. [`pre-commit`](https://pre-commit.com/) with the `trailing-whitespace` and `end-of-file-fixer` hooks) that can automatically fix whitespace errors.

**Comment by ruddell** [comment]
Thanks again. Merging since the pipeline failure looks to be related to some Xcode changes

I turned on whitespace trimming in VSCode so I hopefully won't add more extra spaces.  I'll also add `md` files to the `prettier` config which should help keep this maintained.

**Comment by friederbluemle** [comment]
Great, thanks @ruddell 👍

**Pull request merged**
